credentials:
  usernames:
    sanju:
      email: sanju@gmail.com 
      name: sanju
      password: "123@abc" # To be replaced with hashed password
    tzvi:
      email: tzvi@gmail.com 
      name:  Tzvi
      password:  "dsfjhk" # this is plane text, use hashed password
cookie:
  expiry_days: 0
  key: PPuSyqhOw6pnp5jh4kpKFws #used for cookie authentication 
  name: kWTIFgPqEl19 #cookie name
preauthorized:
  emails:
  - melsby@gmail.com 
